style
style
	^ 'button.reaction {
		background-color: rgb(23, 163, 128);
		width: 90px;
		border-radius: 50px;
		float: left}
		
		button:hover {
      background: rgba(131, 131, 131, 0.774);
	   transition: all 0.4s linear;}
		
		.newpost{
		position: absolute;
		bottom: 310px;
		right: 900px;
		background-color: rgb(185, 185, 211);}
		
		.logout{
		position: fixed;
		right: 0;
		bottom: 500px;}
		
		.cover{
		position: fixed;
		width: 100%;
		height: 100%;
		z-index: -1;
		background-color:rgb(159, 219, 196)}'